### PR TITLE
set timeout

### PR DESCRIPTION
**Pull request by abbyfleming**
## Description
A setTimeout was created to ensure that the user's location was added to FB before being pulled back down. Would like to revisit this in the future to see if the getLocation() function can be converted into a promise to have proper chaining.

### CODE REVIEW

**Comment by hfrankst** [comment]
looks great

**Review by Deanomatic — APPROVED** [review]

**Comment by Deanomatic** [comment]
🍔

**Comment by Deanomatic** [comment]
⚒

**Comment by Deanomatic** [comment]
👂

**Pull request merged**
