### PR TITLE
add radius to the lat long

### PR DESCRIPTION
**Pull request by abbyfleming**
## Description
This PR covers adding in the radius to the coordinate object. This will allow us to pass in the radius as a twitter query. 

screen shot 2017-03-11 at 1 29 07 pm

### CODE REVIEW

**Comment by hfrankst** [comment]
👍

**Comment by thenicknash** [comment]
Hi

**Comment by thenicknash** [comment]
How are you

**Comment by thenicknash** [comment]
I'm doing good.

**Pull request merged**
